// @ts-nocheck
import * as __fd_glob_50 from "../content/docs/components/typography.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/components/toggle.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/components/toggle-group.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/components/textarea.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/components/text.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/components/tabs.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/components/table.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/components/switch.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/components/spinner.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/components/skeleton.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/components/sheet.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/components/separator.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/components/select.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/components/scroll-area.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/components/resizable.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/components/radio-group.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/components/progress.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/components/popover.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/components/pagination.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/components/navigation-menu.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/components/menubar.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/components/label.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/components/input.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/components/input-otp.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/components/input-group.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/components/hover-card.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/components/field.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/components/empty.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/components/dropdown-menu.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/components/drawer.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/components/dialog.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/components/context-menu.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/components/command.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/components/combobox.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/components/collapsible.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/components/checkbox.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/components/chart.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/components/carousel.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/components/card.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/components/calendar.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/components/button.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/components/button-group.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/components/breadcrumb.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/components/badge.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/components/avatar.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/components/aspect-ratio.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/components/alert.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/components/alert-dialog.mdx?collection=docs"
import * as __fd_glob_2 from "../content/docs/components/accordion.mdx?collection=docs"
import * as __fd_glob_1 from "../content/docs/index.mdx?collection=docs"
import * as __fd_glob_0 from "../content/docs/getting-started.mdx?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {}, {"getting-started.mdx": __fd_glob_0, "index.mdx": __fd_glob_1, "components/accordion.mdx": __fd_glob_2, "components/alert-dialog.mdx": __fd_glob_3, "components/alert.mdx": __fd_glob_4, "components/aspect-ratio.mdx": __fd_glob_5, "components/avatar.mdx": __fd_glob_6, "components/badge.mdx": __fd_glob_7, "components/breadcrumb.mdx": __fd_glob_8, "components/button-group.mdx": __fd_glob_9, "components/button.mdx": __fd_glob_10, "components/calendar.mdx": __fd_glob_11, "components/card.mdx": __fd_glob_12, "components/carousel.mdx": __fd_glob_13, "components/chart.mdx": __fd_glob_14, "components/checkbox.mdx": __fd_glob_15, "components/collapsible.mdx": __fd_glob_16, "components/combobox.mdx": __fd_glob_17, "components/command.mdx": __fd_glob_18, "components/context-menu.mdx": __fd_glob_19, "components/dialog.mdx": __fd_glob_20, "components/drawer.mdx": __fd_glob_21, "components/dropdown-menu.mdx": __fd_glob_22, "components/empty.mdx": __fd_glob_23, "components/field.mdx": __fd_glob_24, "components/hover-card.mdx": __fd_glob_25, "components/input-group.mdx": __fd_glob_26, "components/input-otp.mdx": __fd_glob_27, "components/input.mdx": __fd_glob_28, "components/label.mdx": __fd_glob_29, "components/menubar.mdx": __fd_glob_30, "components/navigation-menu.mdx": __fd_glob_31, "components/pagination.mdx": __fd_glob_32, "components/popover.mdx": __fd_glob_33, "components/progress.mdx": __fd_glob_34, "components/radio-group.mdx": __fd_glob_35, "components/resizable.mdx": __fd_glob_36, "components/scroll-area.mdx": __fd_glob_37, "components/select.mdx": __fd_glob_38, "components/separator.mdx": __fd_glob_39, "components/sheet.mdx": __fd_glob_40, "components/skeleton.mdx": __fd_glob_41, "components/spinner.mdx": __fd_glob_42, "components/switch.mdx": __fd_glob_43, "components/table.mdx": __fd_glob_44, "components/tabs.mdx": __fd_glob_45, "components/text.mdx": __fd_glob_46, "components/textarea.mdx": __fd_glob_47, "components/toggle-group.mdx": __fd_glob_48, "components/toggle.mdx": __fd_glob_49, "components/typography.mdx": __fd_glob_50, });